- hosts: localhost
  become: true
  roles:
  - firefox
  - yarn
  - docker

  collections:
  - basvandenbrink.firefox

  vars:
    username: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    wallpapers: "{{ lookup('env', 'HOME') }}/Wallpapers"

    firefox_profiles:
      default:
        extensions:
          - decentraleyes

  pre_tasks:
  - name: Verify Ansible meets MrDev minimal requirements
    assert:
      that: "ansible_version.full is version_compare('2.9', '>=')"
      msg: >
          "You must update Ansible to at least 2.9 to use this version of MrDev."


  tasks:
#   - include: ansible-tasks/kernel/ubuntu18.04-tunning.yml
#   - include: ansible-tasks/apt-packages/ubuntu18.04-install-apt-packages.yml
   - include: ansible-tasks/theme/main.yml
#   - include: ansible-tasks/snap-packages/ubuntu18.04-install-snap-packages.yml
#   - include: ansible-tasks/openjdk11/ubuntu18.04-install-openjdk11.yml
#   - include: ansible-tasks/visualstudiocode/ubuntu18.04-install-visualstudiocode.yml
