- hosts: localhost
  become: true
  tasks:
#  - include: ansible-tasks/packages/ubuntu18.04-install.yml
#  - include: ansible-tasks/docker/ubuntu18.04-install.yml
#  - include: ansible-tasks/yarn/ubuntu18.04-install-yarn.yml
  - include: ansible-tasks/visualstudiocode/ubuntu18.04-install-visualstudiocode.yml
