- hosts: localhost
  become: true

  vars:
    username: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    wallpapers: "{{ lookup('env', 'HOME') }}/Wallpapers"

  pre_tasks:
  - name: Verify Ansible meets MrDev minimal requirements
    assert:
      that: "ansible_version.full is version_compare('2.9', '>=')"
      msg: >
          "You must update Ansible to at least 2.9 to use this version of MrDev."
  roles:
  - ambiente
  - yarn
  - docker
  - inep

