roles:
  - name: basvandenbrink.firefox
  - name: kami911.java_open_jdk11
  - name: basvandenbrink.firefox
  - name: gantsign.oh-my-zsh
collections:
  - name: community.general
  - name: moreati.psutil

