---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: build container image
      docker_image:
        name: democontainer:v1.0
        build:
          path: /root/demo-dockerfile
          source: build
        state: present
